In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [4]:
b = [1,2,3]
print(b)
b

[1, 2, 3]


[1, 2, 3]

In [5]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
c

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
d = ([[1,2,3],[4,5,6],[7,8,9]])
print(d)
d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

jumlah item dalam sebuah numpy array secara row ( axis 2) harus imbang, selalu sama. setiap row punya jumlah item yang sama

- shortcut lain untuk numpy selain np.array([])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(7)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 2.11392033e-307])

In [10]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
lima = np.arange(5,101,5) # isinya mulai,akhir,jaraknya
lima

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

## add, remove, sort

In [12]:
np.append(a,c)

array([1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.zeros(2)
b = np.ones(3)

np.append(a,b)

array([0., 0., 1., 1., 1.])

In [14]:
np.append(a, [1,2,3])

array([0., 0., 1., 2., 3.])

In [15]:
np.delete(lima, 1)

array([  5,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [16]:
acak = np.array([12,6,23,78,9,4,-12,4,-12,-5,0])
acak


array([ 12,   6,  23,  78,   9,   4, -12,   4, -12,  -5,   0])

In [17]:
tersortir = np.sort(acak)
tersortir

array([-12, -12,  -5,   0,   4,   4,   6,   9,  12,  23,  78])

In [18]:
acak

array([ 12,   6,  23,  78,   9,   4, -12,   4, -12,  -5,   0])

## melihat shape and size array

In [19]:
array3d = np.array([
    [[1,2,1,2],[3,4,2,1]],
    [[5,6,7,8],[7,8,6,5]],
    [[9,0,3,5],[1,2,3,4]]
])

In [20]:
np.ndim(array3d)

3

In [21]:
np.shape(array3d) # kita akan dapat (3,2,4) yang artinya di level pertama ada 3 item 
#setiap item tersebut(level2) isinya ada 2 item
#setiap elemen tersebut (level 3) ada 4 barang lagi

(3, 2, 4)

In [22]:
np.size(array3d)

24

In [23]:
array3d.ndim

3

In [24]:
array3d.shape

(3, 2, 4)

In [25]:
array3d.size

24

## reshape

In [26]:
hasil_reshape = array3d.reshape(4,6)
hasil_reshape

array([[1, 2, 1, 2, 3, 4],
       [2, 1, 5, 6, 7, 8],
       [7, 8, 6, 5, 9, 0],
       [3, 5, 1, 2, 3, 4]])

In [27]:
hasil_reshape = array3d.reshape(24,1)
hasil_reshape

array([[1],
       [2],
       [1],
       [2],
       [3],
       [4],
       [2],
       [1],
       [5],
       [6],
       [7],
       [8],
       [7],
       [8],
       [6],
       [5],
       [9],
       [0],
       [3],
       [5],
       [1],
       [2],
       [3],
       [4]])

In [28]:
hasil_reshape = array3d.reshape(2,3,4)
hasil_reshape

array([[[1, 2, 1, 2],
        [3, 4, 2, 1],
        [5, 6, 7, 8]],

       [[7, 8, 6, 5],
        [9, 0, 3, 5],
        [1, 2, 3, 4]]])

## menambah dimensi array

In [29]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [30]:
arr.ndim

1

In [31]:
arr2 = arr[np.newaxis, :] # merubah array 1 jadi 2 dimensi. cara lain: np.expand_dims(arr, axis=0)
arr2

array([[0, 1, 2, 3, 4, 5]])

In [32]:
arr2.ndim

2

In [33]:
arr3 = arr[:, np.newaxis]# merubah array 1 jadi 2 dimensi cara lain: np.expand_dims(arr, axis=1)
arr3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

apa perbedaan arr[np.newaxis, :] dengan arr[:, np.newaxis]?
bedanya adalah axis mana yang ditambahkan menjadi dimensi baru.
untuk yang pertama, dia akan tambahin di axis 0 (row)
untuk yang kedua, dia akan tambahin di axis 1 (coloumn)

In [34]:
# cara lain selain pakai np.newaxis adalah dengan np.expand_dims
np.expand_dims(arr, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [35]:
np.expand_dims(arr, axis=0)

array([[0, 1, 2, 3, 4, 5]])

## indexing dan slicing
indexing adalah mengambil 1 item di array/ list menggunakan index nya

slicing adalah mengambil satu item set di arrat/list menggunakan index juga

In [36]:
arr

array([0, 1, 2, 3, 4, 5])

In [37]:
arr[0:3]

array([0, 1, 2])

In [38]:
arr[-2:]

array([4, 5])

In [39]:
arr[3]

3

In [40]:
new = arr[1:5] # kalau hasilnya mau disimpan, masukan ke variable
new

array([1, 2, 3, 4])

In [41]:
arr # arr tidak diubah oleh indexing ataupun slicing

array([0, 1, 2, 3, 4, 5])

In [42]:
acak = np.array([12,6,23,78,9,4,-12,4-9,0])
acak

array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])

In [43]:
acak[acak>0] # numpy array bisa terima kondisi sebagai indexnya juga

array([12,  6, 23, 78,  9,  4])

In [44]:
acak # tetap tidak merubah array awalnya

array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])

In [45]:
lebih_dari_0 = (acak>0)
acak[lebih_dari_0]

array([12,  6, 23, 78,  9,  4])

In [46]:
acak_genap = acak[acak % 2 == 0] # kita ambil angka yang genap saja
acak_genap

array([ 12,   6,  78,   4, -12,   0])

In [47]:
acak_genap_lebih_dari_0 = acak[(acak % 2 == 0) & (acak > 0)] # pakai dan
acak_genap_lebih_dari_0

array([12,  6, 78,  4])

In [48]:
acak_genap_lebih_dari_0 = acak[(acak % 2 == 0) | (acak > 0)] # pakai atau
acak_genap_lebih_dari_0

array([ 12,   6,  23,  78,   9,   4, -12,   0])

## teknik lain untuk membuat numpy array

- vstack: vertical stack
- hstack: horizontal stack
- hsplit: horizontal split

In [49]:
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
arr_tumpuk12 = np.vstack((arr1,arr2))
# jadilah array 2 dimensi hasil menumpuk atau stack
arr_tumpuk12
        

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [50]:
arr1 = np.array([[10,11],[12,13],[14,15]])
arr2 = np.array([[20,21],[22,23],[24,25]])
arr_tumpuk12 = np.vstack((arr1,arr2))

arr_tumpuk12
        

array([[10, 11],
       [12, 13],
       [14, 15],
       [20, 21],
       [22, 23],
       [24, 25]])

In [51]:
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
arr_tumpuk12 = np.hstack((arr1,arr2))
# jadilah array 2 dimensi hasil menumpuk dari kiri ke kanan
arr_tumpuk12
        

array([10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25])

In [52]:
arr1

array([10, 11, 12, 13, 14, 15])

In [53]:
arr2

array([20, 21, 22, 23, 24, 25])

In [54]:
arr1 = np.array([[10,11],[12,13],[14,15]])
arr2 = np.array([[20],[22],[24]])
arr_tumpuk12 = np.hstack((arr1,arr2))

arr_tumpuk12

array([[10, 11, 20],
       [12, 13, 22],
       [14, 15, 24]])

In [55]:
arr1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [56]:
arr2

array([[20],
       [22],
       [24]])

In [57]:
arr1 = np.array([[10,11],[12,13],[14,15]])
arr2 = np.array([[20,21,22,23,24,25]])
arr_tumpuk12 = np.hstack((arr1,arr2))

arr_tumpuk12

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [58]:
arr1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [59]:
arr2

array([[20, 21, 22, 23, 24, 25]])

hsplit membagi array menjadi banyak

In [60]:
arr3 =np.array([[10,11,12,13,14,15],
               [20,21,22,23,24,25]])
arr3.size

12

In [61]:
hasil_split =np.hsplit(arr3,3) # membuat array baru menjadi array lama
hasil_split

[array([[10, 11],
        [20, 21]]),
 array([[12, 13],
        [22, 23]]),
 array([[14, 15],
        [24, 25]])]

In [62]:
arr3 # tidak berubah

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [63]:
np.hsplit(arr3,7) # error karena arr3 isinya ada 12 item, dia bisa dibagi 3
# misalkan kita bagi 7, pemagiannya tidak imbang

ValueError: array split does not result in an equal division

In [64]:
# view arr4 hanya menunjukan ke rumah arr3, shallow copy
arr4 =arr3.view()

# arr4 membuat rumah sendiri dengan isi item yang sama
# arr3 punya, deep copy
arr4 = arr3.copy()

## numpy array isinya bisa dihitung langsung

semua numpy array bisa kita tambah kurang kali bagi dll ke angka atau ke numpy array lainnya

In [65]:
arr3

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [66]:
arr3 + 1

array([[11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26]])

In [67]:
arr3 - 10

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

In [68]:
arr3 * 2

array([[20, 22, 24, 26, 28, 30],
       [40, 42, 44, 46, 48, 50]])

In [69]:
arr3 / 5

array([[2. , 2.2, 2.4, 2.6, 2.8, 3. ],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. ]])

In [70]:
arr3.sum()

210

In [71]:
arr5 = np.array([[5],[10]])
arr5.sum()

15

In [72]:
arr3.sum(axis=0) #yang ditamabah rownya

array([30, 32, 34, 36, 38, 40])

In [73]:
arr3.sum(axis=1) # yang ditambah semua kolomnya

array([ 75, 135])

In [74]:
panjang = np.array([30,20,40,15])
lebar = np.array([20,10,50,70])
tinggi = np.array([5,10,15,20])

In [75]:
area = panjang * lebar
area

array([ 600,  200, 2000, 1050])

In [76]:
volume = area * tinggi
volume

array([ 3000,  2000, 30000, 21000])

In [77]:
hari_senin = np.array([10,20,50])
hari_selasa = np.array([100,0,10])

penjualan = hari_senin + hari_selasa
penjualan

array([110,  20,  60])

## array operation lainnya
- maximum
- minimum
- sum
- rata rata

In [78]:
acak

array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])

In [79]:
acak.max()

78

In [80]:
acak.min()

-12

In [81]:
acak.sum()

115

In [82]:
acak.mean()

12.777777777777779

In [83]:
M = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
print(M.sum(axis=0))
print(M.mean(axis=0))
print(M.max(axis=0))
print(M.min(axis=0))

[12 15 18]
[4. 5. 6.]
[7 8 9]
[1 2 3]


In [85]:
print(M.sum(axis=1))
print(M.mean(axis=1))
print(M.max(axis=1))
print(M.min(axis=1))

[ 6 15 24]
[2. 5. 8.]
[3 6 9]
[1 4 7]


- product (dot product untuk matrix)
- standart deviation(angka statistik)

In [86]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [7,8],
    [9,10],
    [11,12]
])

In [87]:
np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

In [88]:
np.std(A)

1.707825127659933

## transpose & reshape

In [89]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
A

array([[1, 2, 3],
       [4, 5, 6]])

## mengurangi dimensi sebuah numpy
- flatten : bikin array baru, deep
- ravel : referensi array lama, shallow

In [93]:
A. flatten()

array([1, 2, 3, 4, 5, 6])

In [95]:
A.ravel()

array([1, 2, 3, 4, 5, 6])

In [96]:
A

array([[1, 2, 3],
       [4, 5, 6]])

## formula matematika 
bisa ditulis di python menggunakan bantuan numpy array

In [98]:
a = np.array([[1,2,3]])
b = np.array([[9,10,11]])
print(a.shape,b.shape)
b = b.T
print(b.shape)

(1, 3) (1, 3)
(3, 1)


In [99]:
b.T

array([[ 9, 10, 11]])

In [100]:
b = b.T
b

array([[ 9, 10, 11]])